apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: isf-operator
  namespace: ibm-spectrum-fusion-ns
spec:
  channel: v2.0
  installPlanApproval: Automatic
  name: isf-operator
  source: isf-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: isf-operator.v2.2.0