apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  labels:
    app: {{ .Values.mq_instance_dr.name }}-sample
  name: {{ .Values.mq_instance_dr.name }}-drpc
spec:
  drPolicyRef:
    name: {{ .Values.mq_instance_dr.odr_policy }}     ## <-- Modify to specify desired DRPolicy and RPO
  placementRef:
    kind: PlacementRule
    name: {{ .Values.mq_instance_dr.name }}-placement
  preferredCluster: {{ .Values.mq_instance_dr.preferredCluster }}
  pvcSelector:
    matchLabels:
      {{ .Values.mq_instance_dr.matchLabel }}  
  {{- if (eq $.Values.mq_instance_dr.action "Failover")  -}}
  action: {{ .Values.mq_instance_dr.action }}
  failoverCluster: {{ .Values.mq_instance_dr.failoverCluster }}
  {{- end -}}
  
  {{- if and (eq $.Values.mq_instance_dr.action "Relocate")  -}}
  action: {{ .Values.mq_instance_dr.action }}
  {{- end -}}
  
