apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: {{ .Values.mq_instance_dr.name }}
  namespace: {{ .Values.mq_instance_dr.namespace }}
  annotations:
    apps.open-cluster-management.io/git-branch: {{ .Values.mq_instance_dr.git_branch }}
    apps.open-cluster-management.io/git-path: {{ .Values.mq_instance_dr.git_folder }}
  labels:
    app: {{ .Values.mq_instance_dr.name }}
    app.kubernetes.io/part-of: {{ .Values.mq_instance_dr.name }}
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  channel: {{ .Values.mq_instance_dr.namespace }}/{{ .Values.mq_instance_dr.name }}
  placement:
    placementRef:
      name: {{ .Values.mq_instance_dr.name }}-placement
      kind: PlacementRule
  posthooks: {}
  prehooks: {}