kind: Secret
apiVersion: v1
metadata:
  name: ibm-spectrum-scale-csi-secret
  namespace: ibm-spectrum-scale-csi
data:
  password: {{ .Values.fusion.csi_secret_password }}
  username: {{ .Values.fusion.csi_secret_user }}
type: kubernetes.io/basic-auth