kind: Secret
apiVersion: v1
metadata:
  name: ibm-spectrum-scale-csi-secret-{{ .Values.fusion.remotecluster_id }}
  namespace: ibm-spectrum-scale
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale-csi
    app.kubernetes.io/name: csi
data:
  password: {{ .Values.fusion.csi_secret_password }}
  username: {{ .Values.fusion.csi_secret_user }}
type: kubernetes.io/basic-auth