kind: Secret
apiVersion: v1
metadata:
  name: ibm-spectrum-scale-csi-secret-{{ .Values.fusion.remotecluster_id }}
  namespace: ibm-spectrum-fusion-ns
data:
  password: {{ .Values.fusion.csi_secret_password }}
  username: {{ .Values.fusion.csi_secret_user }}
type: kubernetes.io/basic-auth