kind: Secret
apiVersion: v1
metadata:
  name: ibm-spectrum-fusion-scale-gui-secret-{{ .Values.fusion.remotecluster_id }}
  namespace: ibm-spectrum-fusion-ns
data:
  password: {{ .Values.fusion.gui_secret_password }}
  username: {{ .Values.fusion.gui_secret_user }}
type: kubernetes.io/basic-auth
