kind: Secret
apiVersion: v1
metadata:
  name: ibm-spectrum-scale-gui-secret
  namespace: ibm-spectrum-scale
data:
  password: {{ .Values.fusion.gui_secret_password }}
  username: {{ .Values.fusion.gui_secret_user }}
type: kubernetes.io/basic-auth
