apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-aiops-orchestrator
  namespace: openshift-operators
spec:
  {{- toYaml .Values.subscriptions.subscription | nindent 2 }}
  channel: v3.3
  installPlanApproval: Automatic
  name: ibm-aiops-orchestrator
  source: ibm-aiops-catalog
  sourceNamespace: openshift-marketplace