apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr                                    
  namespace: cpd-instance                             
spec:
  nodeSelector:
    node-role.kubernetes.io/cloud-paks: "true"
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/cloud-paks
      value: 'true'
      operator: Equal
  defaultRoute: true
  license:
    accept: true
    license: Enterprise                 
  storageClass: {{ .Values.cp4data.storageclass }}                    
  version: "4.0.1"