kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "110"
    helm.sh/hook-weight: "110"
apiVersion: v1
data: {{ .Values.ocs.configmap }}
  
