kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ocs-initial
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: ibm-vpc-block-csi-driver
    razee/force-apply: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    helm.sh/hook-weight: "100"
    armada-service: addon-vpc-block-csi-driver
provisioner: vpc.block.csi.ibm.io
parameters:
  billingType: hourly
  classVersion: '1'
  csi.storage.k8s.io/fstype: ext4
  encrypted: 'false'
  encryptionKey: ''
  profile: 10iops-tier
  region: ''
  resourceGroup: ''
  sizeRange: '[10-2000]GiB'
  tags: ''
  zone: ''
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
