apiVersion: ocs.ibm.io/v1
kind: OcsCluster
metadata:
  annotations:    
  name: ocscluster-vpc
spec:
  monStorageClassName:  {{ .Values.odf.storageClass }}
  monSize: 20Gi
  osdStorageClassName: {{ .Values.odf.storageClass }}
  osdSize: {{ .Values.odf.sizeOSD }} 
  numOfOsd: 3
  billingType: {{ .Values.odf.billingType }} 
  ocsUpgrade: false
  workerNodes: 
    - {{ .Values.odf.worker_ip_1 }} 
    - {{ .Values.odf.worker_ip_2 }}
    - {{ .Values.odf.worker_ip_3 }}
