kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ocs-initial
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: ibm-vpc-block-csi-driver
    razee/force-apply: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    helm.sh/hook-weight: "100"
    armada-service: addon-vpc-block-csi-driver
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"armada-service":"addon-vpc-block-csi-driver","razee.io/build-url":"https://travis.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/builds/53951456","razee.io/source-url":"https://github.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/commit/8f3f02558d7b09651e20b77799371a9a8f356645","version":"3.0.1_738"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"ibm-vpc-block-csi-driver","razee/force-apply":"true"},"name":"ibmc-vpc-block-metro-10iops-tier"},"parameters":{"billingType":"hourly","classVersion":"1","csi.storage.k8s.io/fstype":"ext4","encrypted":"false","encryptionKey":"","profile":"10iops-tier","region":"","resourceGroup":"","sizeRange":"[10-2000]GiB","tags":"","zone":""},"provisioner":"vpc.block.csi.ibm.io","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
    razee.io/build-url: >-
      https://travis.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/builds/53951456
    razee.io/source-url: >-
      https://github.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/commit/8f3f02558d7b09651e20b77799371a9a8f356645
    version: 3.0.1_738
provisioner: vpc.block.csi.ibm.io
parameters:
  billingType: hourly
  classVersion: '1'
  csi.storage.k8s.io/fstype: ext4
  encrypted: 'false'
  encryptionKey: ''
  profile: 10iops-tier
  region: ''
  resourceGroup: ''
  sizeRange: '[10-2000]GiB'
  tags: ''
  zone: ''
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
