kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ibm-spectrum-scale-csi-fileset
provisioner: spectrumscale.csi.ibm.com
parameters:
  clusterId: {{ .Values.cnsa.cluster_id }}
  volBackendFs: spectrum-1-fs0
reclaimPolicy: Delete