apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    helm.sh/hook-weight: "20"
  name: cluster
  namespace: {{ .Values.namespace }}
spec:
  prometheus:
    enabled: true
    service:
      port: 8080
  resources:
   requests:
     cpu: 10m
     memory: 96Mi
   limits:
     cpu: 100m
     memory: 256Mi