apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    helm.sh/hook-weight: "0"
  name: external-secrets-operatorgroup
  namespace: {{ .Values.namespace }}
spec:
  targetNamespaces:
  - external-secrets