apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: {{ .Values.mq-instance.name }} 
  namespace: {{ .Values.mq-instance.namespace }} pak
spec:
  license:
    accept: true
    license: L-RJON-BUVMQX
    metric: VirtualProcessorCore
    use: NonProduction
  queueManager:
    metrics:
      enabled: true
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: '1'
        memory: 1Gi
    readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    route:
      enabled: true
    name: {{ .Values.mq-instance.name }} 
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 90
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    imagePullPolicy: IfNotPresent
    debug: false
    logFormat: Basic
    availability:
      type: MultiInstance
    storage:
      defaultClass: {{ .Values.mq-instance.storage-class }} 
      persistedData:
        class: {{ .Values.mq-instance.storage-class }} 
        enabled: true
        size: 5Gi
        type: persistent-claim
      queueManager:
        class: {{ .Values.mq-instance.storage-class }} 
        size: 20Gi
        type: persistent-claim
      recoveryLogs:
        class: {{ .Values.mq-instance.storage-class }} 
        enabled: true
        size: 5Gi
        type: persistent-claim
  securityContext:
    initVolumeAsRoot: false
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
          resources: {}
  terminationGracePeriodSeconds: 30
  tracing:
    agent: {}
    collector: {}
    enabled: false
    namespace: ''
  version: 9.2.1.0-r1
  web:
    enabled: true
