apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: {{ .Values.mq_instance.name }}
  namespace: {{ .Values.mq_instance.namespace }}
spec:
  license:
    accept: true
    license: L-RJON-BZFQU2
    metric: VirtualProcessorCore
    use: NonProduction
  tracing:
    agent: {}
    collector: {}
    enabled: false
    namespace: ''
  terminationGracePeriodSeconds: 30
  pki:
    keys:
      - name: default
        secret:
          items:
            - tls.key
            - tls.crt
          secretName: {{ .Values.mq_instance.tls }}
  securityContext:
    initVolumeAsRoot: false
  web:
    enabled: false
  version: {{ .Values.mq_instance.version }}
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
          resources: {}
  queueManager:
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
    readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    route:
      enabled: true
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 0
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    imagePullPolicy: IfNotPresent
    debug: false
    startupProbe:
      failureThreshold: 24
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    mqsc:
      - configMap:
          items:
            - nativehamqsc.mqsc
          name: {{ .Values.mq_instance.configmap }}
    logFormat: Basic
    availability:
      type: NativeHA
      updateStrategy: RollingUpdate
    storage:
      defaultClass: {{ .Values.mq_instance.storage_class }}
      persistedData:
        enabled: false
      queueManager:
        size: 2Gi
        type: persistent-claim
      recoveryLogs:
        enabled: false




  web:
    enabled: true
