apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    helm.sh/hook-weight: "200"
  name: turbonomic-og
  namespace: turbonomic
spec:
  targetNamespaces:
  - turbonomic